
# https://github.com/nodejs/docker-node/blob/master/README.md#how-to-use-this-image

version: "3"
services:

services:
  ad.frontend:
    container_name: ad.frontend
    image: trion/ng-cli
    working_dir: /home/node/app
    environment:
      PORT: 3000
      NODE_ENV: development
    volumes:
      - ./frontend:/home/node/app
    expose:
      - "3000"
    ports:
      - 3000:3000
    command: bash -c 'npm install && npm start'
